version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:v1.3.0
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:v1.4
    environment:
      MEILI_NO_ANALYTICS: "true"
    restart: unless-stopped
    ports:
      - "7700:7700"

  n8n:
    image: n8nio/n8n:1
    restart: unless-stopped
    environment:
      - GENERIC_TIMEZONE=America/New_York
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - valkey

  backend:
    build: ./apps/backend
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - HF_API_TOKEN=${HF_API_TOKEN}
      - POSTGRES_URL=${POSTGRES_URL}
      - QDRANT_URL=${QDRANT_URL}
      - REDIS_URL=${REDIS_URL}
      - MEILISEARCH_HOST=${MEILISEARCH_HOST}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - qdrant
      - valkey
      - meilisearch

  frontend:
    build: ./apps/frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  qdrant_data:
  n8n_data:
